# NumPy

In [3]:
import numpy as np
#1st method
myArray=np.array([1,2,3,4])
print(myArray)

[1 2 3 4]


In [4]:
#checking library version
np.__version__


'1.20.1'

# Different Dimensional Arrays

# 1) OneD array

In [7]:
#1st method
oneD=np.array([1,2,3,4,5,6])
print(oneD)

[1 2 3 4 5 6]


In [6]:
#2ndmethod
ele=[1,2,3,4,5,6]
oneD=np.array(ele)
print(oneD)

[1 2 3 4 5 6]


# Mutidimensional Array


# 2D Array

In [10]:
#1st method
twoD=np.array([[1,2,3],[4,5,6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


In [11]:
#2nd method
ele=[[1,2,3],[4,5,6]]
twoD=np.array(ele)
print(twoD)

[[1 2 3]
 [4 5 6]]


# Creating ndArrays with Zeros

In [12]:
#1st method
y=np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [15]:
#2nd method
x=np.zeros((2,3),dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0]])

# Creating ndArrays with Ones

In [16]:
#1st method
y=np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [17]:
#2nd method
x=np.ones((5,5),dtype=int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Numpy Array attributes
* Each array has feature like shape, size and number of dimensions

# 1.NdArray.Shape
* it returns a tuple of array dimension

In [18]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim
print(a.shape)

(2, 3)


# Random  number 

* The random module in numpy package contains many functions for generation of random numbers.

# 1. numpy.random.rand()

*Generate 10 Random floats

In [21]:
x=np.random.rand(10)
x.ndim
print(x.shape)
x

(10,)


array([3.49794885e-01, 6.43167065e-01, 6.58862458e-01, 6.39380142e-01,
       7.90686452e-01, 5.73012272e-01, 9.20422259e-02, 1.76190062e-04,
       1.24211579e-01, 8.33555338e-01])

# Generate random integer from given range

In [23]:
x=np.random.randint(1,100,size=30)
x

array([14, 88, 39, 20, 11, 67, 74, 83, 54, 59, 89,  1,  3, 17, 53, 12, 87,
       71,  2, 10, 51, 99, 68, 39, 44, 49, 46, 54, 18, 32])

In [24]:
#Generate a (3,2)vector 
x=np.random.randint(1,100,size=(3,2))
x

array([[97, 22],
       [99, 25],
       [42, 87]])

# Generate random number from array
* The choice() method allows you to generate a random value based on an array of values  

In [25]:
# Generate a random number from a list of element [1,2,3,4,5,6,7,8]
x=np.random.choice([1,2,3,4,5,6,7,8])
x

7

In [26]:
# Generate multiple random numbers from a list of element [1,2,3,4,5,6,7,8]
x=np.random.choice([1,2,3,4,5,6,7,8],size=3)
x

array([5, 5, 8])

# Accessing elements from an array
* Indexing in numpy is quite similar topython's list standard

In [27]:
# In 1D 
x=np.array([10,23,45,56])
x[3]

56

In [30]:
# In Multidimension
# 1st method

x=np.array([[22,34,54],[33,76,21]])
print(x[0][1])
print(x[1][1])

34
76


# Indexing and Slicing
* Basic Slicing

In [31]:
x=np.array([10,23,45,4,22,14,56,98,77,102,11])
x[1:9:3]

array([23, 22, 98])

In [32]:
x=np.array([[23,45,32],[35,76,85],[22,11,44],[26,93,46]])
x[1:]

array([[35, 76, 85],
       [22, 11, 44],
       [26, 93, 46]])

# Fancy Indexing
* Here we apply indexing on both rows and columns simultenously

In [33]:
x=np.random.randint(100,size=(10,6))
x

array([[92, 81, 83, 47, 48, 87],
       [87,  3, 68,  1, 67, 91],
       [49, 93, 84, 36, 77, 99],
       [67, 56, 31, 90, 47, 50],
       [55, 78,  0, 59,  8, 58],
       [ 6, 25,  9, 58, 72, 12],
       [40, 91, 36, 55, 76, 87],
       [72, 61, 80, 59, 58, 86],
       [47, 34, 73, 48, 56, 29],
       [27, 39, 88, 10, 78, 66]])

In [34]:
#printing 2nd, 4th and 6th column
x[:,[1,3,5]]

array([[81, 47, 87],
       [ 3,  1, 91],
       [93, 36, 99],
       [56, 90, 50],
       [78, 59, 58],
       [25, 58, 12],
       [91, 55, 87],
       [61, 59, 86],
       [34, 48, 29],
       [39, 10, 66]])

In [38]:
# printin grows from 2 to 7 
x[[1,2,3,4,5,6,7],:]

array([[87,  3, 68,  1, 67, 91],
       [49, 93, 84, 36, 77, 99],
       [67, 56, 31, 90, 47, 50],
       [55, 78,  0, 59,  8, 58],
       [ 6, 25,  9, 58, 72, 12],
       [40, 91, 36, 55, 76, 87],
       [72, 61, 80, 59, 58, 86]])

In [39]:
# printing alternate rows and alternate columns
x[::2,::2]

array([[92, 83, 48],
       [49, 84, 77],
       [55,  0,  8],
       [40, 36, 76],
       [47, 73, 56]])

# Reshaping of an array

In [41]:
#Reshape the nos 1 to 9 in 3x3 grid 
#e.g for 9 elements dimensions should be (3x3) or (1x9) or(9x1)

x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Transposing an array

In [46]:
x=np.arange(1,10).reshape(3,3)
#print(x)
print(f"Transpose of \n{x} \nis \n{x.T}")

Transpose of 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
is 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# np.concatenate

In [47]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 5 6 7 8]


In [49]:
x=np.array([[1,2,3,4],[9,11,12,34]])
y=np.array([[5,6,7,8],[36,76,32,66]])
z=np.concatenate([x,y])
print(z)

[[ 1  2  3  4]
 [ 9 11 12 34]
 [ 5  6  7  8]
 [36 76 32 66]]


# Joining 2D Arrays 

In [55]:
# If axis is not explicitly passed it is taken to be 0 
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nConcatenated matrix when axis=0 is")
np.concatenate([x,y])


[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Concatenated matrix when axis=0 is


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [33, 23,  4, 12],
       [97, 56, 38, 31]])

In [56]:
# when axis = 1
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nConcatenated matrix when axis=1 is")
np.concatenate([x,y],axis=1)

[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Concatenated matrix when axis=1 is


array([[ 1,  2,  3,  4, 33, 23,  4, 12],
       [ 5,  6,  7,  8, 97, 56, 38, 31]])

# Arithmetic operations on matrices


In [57]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nAddition is")
x+y

[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Addition is


array([[ 34,  25,   7,  16],
       [102,  62,  45,  39]])

In [58]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nSubstraction is")
x-y

[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Substraction is


array([[-32, -21,  -1,  -8],
       [-92, -50, -31, -23]])

In [59]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nMultiplication is")
x*y

[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Multiplication is


array([[ 33,  46,  12,  48],
       [485, 336, 266, 248]])

In [60]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[33,23,4,12],[97,56,38,31]])
print(x)
print("\n",y)
print("\nDivision is")
x/y

[[1 2 3 4]
 [5 6 7 8]]

 [[33 23  4 12]
 [97 56 38 31]]

Division is


array([[0.03030303, 0.08695652, 0.75      , 0.33333333],
       [0.05154639, 0.10714286, 0.18421053, 0.25806452]])

# Pandas

* Series is only single column
* DataFrame is a structure which is 2D array.
* Multipe panda series make panda DataFrames.

In [62]:
import pandas as pd
import numpy as np

# Creating Pandas DataFrame from the dictionary

In [63]:
data={'student':['Digvijay','Rutika','Ishwari','Omkar'],'Year':[3,2,3,1],"Marks":[95,96,97,98]}
data

{'student': ['Digvijay', 'Rutika', 'Ishwari', 'Omkar'],
 'Year': [3, 2, 3, 1],
 'Marks': [95, 96, 97, 98]}

In [67]:
df=pd.DataFrame(data)
df

student  Year  Marks
0  Digvijay     3     95
1    Rutika     2     96
2   Ishwari     3     97
3     Omkar     1     98

# Note: the type for column is pandas Series


In [65]:
#type
type(df)

pandas.core.frame.DataFrame

In [66]:
type(df['student'])

pandas.core.series.Series

In [68]:
df['student']

0    Digvijay
1      Rutika
2     Ishwari
3       Omkar
Name: student, dtype: object

In [70]:
print(df['Marks'])
df['Marks'].sum()

0    95
1    96
2    97
3    98
Name: Marks, dtype: int64


386

# Construction of DataFrame

DataFrames can be created from many types of input:
    
    * columns (dict of lists)
    * rows (lists of dicts)
    * CSV file (pd.read_csv)
    * from NumPy ndarray 

# Construction from rows(list of dicts)

In [71]:
l=[{'name':'abc','marks':98},{'name':'bcd','marks':95},{'name':'cde','marks':96,'grade':'A'}]
df=pd.DataFrame(l)
df

name  marks grade
0  abc     98   NaN
1  bcd     95   NaN
2  cde     96     A

# Construction from CSV Files

In [ ]:
df=pd.read_csv('Salary.csv')